### ISSUE TITLE
error with "name" in class BayesianLSTM

### ISSUE THREAD

**Issue by Gloria2** [mirceamironenco/BayesianRecurrentNN#2]
I tried to reproduce the results of given code and got the error like this:
![image](https://user-images.githubusercontent.com/45344125/50064496-8104dd00-01ec-11e9-8a36-6cda06f59df7.png)
can you help figure out why this happened? I haven't started to change the code yet so this's the original one.

**Comment by mirceamironenco** [comment]
Are you using the correct python (3.5+) and tensorflow (1.3.0) version? Did you run it as indicated in the README?

**Comment by Gloria2** [comment]
I'm using python 3.6 and tensorflow 1.10.0 version. Yeah I ran as what it said in README exactly and I think the error is in this part of "name" definition.
![image](https://user-images.githubusercontent.com/45344125/50071248-0b106e00-020c-11e9-988f-7917ef7ca1c3.png)

**Comment by mirceamironenco** [comment]
1.10.0 has changed a lot and most likely has deprecated the LSTM class used in this project. Please use 1.3.0 if you simply want to replicate the results. Feel free to send a pull request to make the code compatible with the newest version.

**Comment by Gloria2** [comment]
oh all my other codes are based on 1.10.0 so I guess it's kind of hard to do the transformation. Would it be possible for you to help make it working with the newest version? I mean...if you have time, I would be very thankful for that.

**Comment by ghost** [comment]
hi @Gloria2 @mirceamironenco were you able to make the adjustments to get it to work for Tensorflow 1.3.0. I would be very grateful if you could share it as I am using 1.3.0 as well.

**Comment by ghost** [comment]
Hi @Gloria2  @mirceamironenco I solved this issue by replacing 'name' with a substitute e.g. 'namex' everywhere in that class.
